name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - dev
    paths-ignore:
      - '.github/workflows/*'


  pull_request:
    types:
      - opened
      - edited 
    branches:
       - main
       - 'dev-*'
       - dev



jobs:

  lint:

   runs-on: ubuntu-latest

   steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: lintng
        run: npm run lint

  Test:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  deploy:
    needs: [lint, Test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploying
        run: echo "deploying..."