name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - 'dev-*'
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - dev
      - 'dev-*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        continue-on-error: true
        id: myTests
        run: npm test

      - name: Upload Test Report
        if: failure() && steps.myTests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.file-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Store Output Variable
        id: publish
        shell: bash
        run: |
          FILE=$(find dist/assets -name "*.js" | head -n 1)
          echo "file-name=$FILE" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Variable
        run: echo "${{ needs.build.outputs.script-file }}"

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Deploy
        run: echo "deploying..."